### PR TITLE
Add input parameter

### PR DESCRIPTION
**Pull request by sabinem**
This PR adds parameters to allow also for a single run os the component using its own example data, that is provided by the tool in the github repo. 

The parameters that are added are 

- `DATA_INPUT_OPTION` which can be either `LOCAL` or `STORAGE`
- `STORAGE_INPUT_PATH` which should be set to `eqasim-matsim-output/simulation_output/eqasim_legs.csv` in case the  component is run in the combination with https://github.com/odtp-org/odtp-eqasim-matsim

### CODE REVIEW

**Comment by caviri** [comment]
Hello @sabinem, thanks! Have you considered using `eqasim-matsim-output/simulation_output/eqasim_legs.csv` as the default value for the path? This would reduce the number of variables from two to one. 

Also, what's the reasoning behind calling it `LOCAL` or `STORAGE`?

**Comment by sabinem** [comment]
@caviri 

> Also, what's the reasoning behind calling it LOCAL or  STORAGE?

The reasoning is that that this is the main point: you want to be able to run the component on it's own: in this case the data is taken from the tool's data `LOCAL`. When the component is part of a workflow, that data is taken from the output of a previous component and from the s3 `STORAGE`: I am open to any renaming that you suggest.

> Have you considered using eqasim-matsim-output/simulation_output/eqasim_legs.csv as the default value for the path? This would reduce the number of variables from two to one.

I think I made it the default value in `odtp.yml` but I don't like to hard code it, since it comes from another component. Hard coding it would create a dependency between these components: what it the the equasim-matsim component changes the shapshot location?

**Comment by caviri** [comment]
Hello @sabinem, thank you for the clarification; however, I would suggest renaming the options to `ORIGINAL_DATA` or `CUSTOM`. The link provided in `STORAGE` is the path of the file from `/odtp/odtp-input/...`, S3 is not being used by this tool. 

`ODTP` v0.4.0 can accept S3 links, but these download and are uncompressed in `/odtp/odtp-input.` However, the `STORAGE_INPUT_PATH` parameter needs to provide the path to the file after this uncompression.

What do you think? We can discuss more tomorrow in our meeting. 

> I think I made it the default value in odtp.yml but I don't like to hard code it, since it comes from another component. 

Yes, I just saw it. My bad. I think it's good as it is.

**Comment by sabinem** [comment]
@caviri I followed up on the requested changes: can you please dev review again? Is there a way to mark parameters as optional?

**Comment by caviri** [comment]
Hello @sabinem, thanks! I approved your changes. We don't have the concept of optional, but it can be included on the odtp.yml under the parameters. I think Robin has this concept on the semantics, I'll double check with him tomorrow.

**Review by caviri — APPROVED** [review]

**Pull request merged**
